apiVersion: v1
kind: Service
# metadata section
metadata:
  name: nginx-service
  labels:
    app: nginx
# specification section
spec:
  selector:
      app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080