apiVersion: v1
kind: Secret
metadata:
  name: mongoexpress-secret
type: Opaque
data:
  ME_CONFIG_BASICAUTH_USERNAME: YWRtaW4=                  # base64 encoded
  ME_CONFIG_BASICAUTH_PASSWORD: RXhwcmVzc0BBZG1pbjIwMjQ=  # base64 encoded