apiVersion: v1
kind: Secret
metadata:
  name: mongoexpress-secret
type: Opaque
data:
  ME_CONFIG_BASICAUTH_USERNAME: YWRtaW4=             # base64 encoded value of 'admin'
  ME_CONFIG_BASICAUTH_PASSWORD: YWRtaW5wYXNz        # base64 encoded value of 'adminpass'