apiVersion: v1
kind: Secret
metadata:
  name: mongoexpress-secret
type: Opaque
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: bW9uZ29hZG1pbg==  # base64 encoded value of 'mongoadmin'
  ME_CONFIG_MONGODB_ADMINPASSWORD: cGFzc3dvcmQ=      # base64 encoded value of 'password'